scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'jmeter'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9270']
